# Generated by Django 3.0 on 2021-04-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0016_auto_20210422_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'Full time'), ('2', 'Part time'), ('3', 'Trial Basis')], max_length=1),
        ),
    ]
